version: '3'
services: 
    api:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports: 
            - "8000:8000"
        volumes: 
            - ./backend/:/backend

    streamlit:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        container_name: "streamlit-frontend"
        ports: 
            - "8501:8501"
        depends_on:
            - api
        volumes: 
            - ./frontend/:/frontend

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/live/vajpet.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
            - /etc/letsencrypt/live/vajpet.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
            - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/snippets/options-ssl-nginx.conf:ro
            - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/certs/ssl-dhparams.pem:ro
        depends_on:
            - streamlit
        ports:
            - "80:80" 
            - "443:443"
    
